#!/bin/bash

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

name=ms-setting

container_id=$(sudo docker container ls | grep "$name" | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
    sudo docker container stop $container_id
fi

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
    git pull
    sudo docker image rm --force "$name"
    sudo docker build --no-cache -t "$name" .
fi

name="ms-setting"; sudo docker run -d -p 5000:3000 "$name"
# sudo docker run -it -p 5000:3000 "$name" /bin/bash
